### ISSUE TITLE
软件录屏时打开其它应用再返回本应用会闪退

### ISSUE THREAD

**Issue by kyriej** [tyhjh/Katarina#1]

**Comment by tyhjh** [comment]
兄弟，闪退的话你把报错信息发出来我看看

**Comment by kyriej** [comment]
大佬，下载项目运行了下，空指针问题，
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yorhp.transcribescreen, PID: 8206
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yorhp.transcribescreen/com.yorhp.transcribescreen.view.activity.MainActivity_}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.yorhp.transcribescreen.module.UserInfo.getUserName()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
        at android.app.ActivityThread.access$1000(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.yorhp.transcribescreen.module.UserInfo.getUserName()' on a null object reference
        at com.yorhp.transcribescreen.view.fragement.MenuListFragment.onCreateView(MenuListFragment.java:55)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
..........

**Comment by tyhjh** [comment]
没发现问题，我更新了一下，空指针可以自己定位改一下，可以拉下了再试一下
